/*
 * MAINDO
 */

//For local / usdivad.com
function main_local() {
	//var rappers;

	//JSON req
	$.getJSON("./src/rapper_stats.json", function(data) {
		//rappers = data;
		//$("#inputForm").append(createForm(data, allParams));
		$("#submitButton").click(function() {
			var r = getSubmit(data);
			$("#results").html(r);
		});
		//getSubmit(data);
		test_parse(data);

	}); //end JSON req
}

//For Wordpress integration
function main_wp() {

	var data = [{"Rapper":"Madlib","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You must be one of America's Most Blunted, because you're Madlib!"},
{"Rapper":"Tyler, The Creator","Decade":"2000s, 2010s","Region":"West Coast","Fashion":"Hipster","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You'd like to stab Bruno Mars in his esophagus. You're Tyler, the Creator!"},
{"Rapper":"Kendrick Lamar","Decade":"2010s","Region":"West Coast","Fashion":"Hipster","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Always changing","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"Macklemore thinks you're awesome. You're Kendrick Lamar."},
{"Rapper":"A$AP Ferg","Decade":"2000s, 2010s","Region":"Mid West, East Coast","Fashion":"Hipster","Tattoos":"many","Food_Fitness_BodyType":"Athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Trap","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You must be a Trap Lord and/or Hood Pope, because you're A$AP Ferg!"},
{"Rapper":"Chief Keef","Decade":"2010s","Region":"Mid West","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Mentally incompetent","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone, Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Bang bang! Stay out of trouble, Chief Keef."},
{"Rapper":"2 Chainz","Decade":"2000s, 2010s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"average","Intelligence":"Dumb","PimpHand":"Legit Pimp","CriminalHistory":"Drug dealer, Drug possession","Sound":"Trap, Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Cocaine","ResultText":"Better step up your neck jewelery game, because you're 2 Chainz!"},
{"Rapper":"Chance The Rapper","Decade":"2010s","Region":"Mid West","Fashion":"Hipster","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Acid","ResultText":"You like LSD so much, you named a mixtape after it. You're Chance the Rapper."},
{"Rapper":"Insane Clown Posse","Decade":"1990s, 2000s, 2010s","Region":"Mid West","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"fat","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Underground/alternative","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Crack, Pills","ResultText":"Fuckin' quizzes, how do they work? You're ICP!"},
{"Rapper":"Danny Brown","Decade":"2010s","Region":"Mid West","Fashion":"Hipster","Tattoos":"a few","Food_Fitness_BodyType":"skinny","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Drug dealer, Drug possession","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Molly, Weed","ResultText":"Like Lieutenant Dan, you're rolling. You're Danny Brown."},
{"Rapper":"Nelly","Decade":"1990s, 2000s, 2010s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"Is it hot in herre, or is it just you? You're Nelly!"},
{"Rapper":"Bone Thugs N Harmony","Decade":"1990s, 2000s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"Skinny","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Dirty South, Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You are Krayzie, Layzie, Bizzy, Wish and Flesh-n all rolled into one. You are Bone Thugs!"},
{"Rapper":"Macklemore","Decade":"2000s, 2010s","Region":"East Coast, West Coast","Fashion":"Avant-garde","Tattoos":"none","Food_Fitness_BodyType":"skinny","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You're the guy in the fur coat with all the Grammys. You're Macklemore."},
{"Rapper":"Eminem","Decade":"1990s, 2000s, 2010s","Region":"East Coast, Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Assault","Sound":"Pop, Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"none","ResultText":"You are the real Slim Shady. Please stand up."},
{"Rapper":"Wiz Khalifa","Decade":"2000s, 2010s","Region":"East Coast, Mid West","Fashion":"Hipster","Tattoos":"many","Food_Fitness_BodyType":"skinny","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"You are Kanye's eskimo bro, Wiz Khalifa."},
{"Rapper":"Drake","Decade":"2000s, 2010s","Region":"East Coast, Dirty South, Mid West","Fashion":"Avant-garde","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop, Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Better be on your worst behavior, because you're Drake."},
{"Rapper":"Wale","Decade":"2000s, 2010s","Region":"East Coast, Dirty South","Fashion":"Upscale","Tattoos":"many","Food_Fitness_BodyType":"Athletic","Intelligence":"Street smart","PimpHand":"Pussy Whipped","CriminalHistory":"None","Sound":"Pop, Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"You went from hipster to gangster in less than sixty secords; you're Wale!"},
{"Rapper":"Pusha T","Decade":"1990s, 2000s, 2010s","Region":"East Coast, Dirty South","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Cocaine","ResultText":"You might sell a brick on your birthday. You are Pusha T."},
{"Rapper":"Lil' Kim","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Legit Pimp","CriminalHistory":"Minor","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"According to Ben Stiller, you're phat. You're Lil' Kim."},
{"Rapper":"P Diddy","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Legit Pimp","CriminalHistory":"Minor","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You're a Bad Boy for life, no matter how many times you change your name."},
{"Rapper":"Nicki Minaj","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"None","ResultText":"You've got the largest barbie collection in the world. You're Nicki Minaj."},
{"Rapper":"Q-Tip","Decade":"1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You're abstract, and we're not talking about Picasso. You're Q-Tip."},
{"Rapper":"Deltron 3030","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"None","ResultText":"In the year 3030, everybody wants to be you. You're Deltron 3030!"},
{"Rapper":"Mos Def","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You're most definitely Mos Def."},
{"Rapper":"Talib Kweli","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"Kanye used to name-drop you to pick up girls. You're Talib Kweli."},
{"Rapper":"Dmx","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed, Cocaine, Crack","ResultText":"Your Wikipedia "},
{"Rapper":"ODB","Decade":"1990s","Region":"East Coast","Fashion":"t shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Dumb","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Crack, Cocaine","ResultText":"You are the Osiris of this shit, AKA Ol' Dirty Bastard."},
{"Rapper":"Beastie Boys","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","ResultText":"You are the Beastie Boys, and you're now officially liscensed to ill."},
{"Rapper":"Black Thought","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"Average","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","ResultText":"On your first day of high school, you had sex with a senior in the bathroom. You're Black Thought."},
{"Rapper":"Run- Dmc","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"Average","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"Peter Piper picked peppers, Run rocked rhymes, and you just took a quiz. You're Run-DMC!"},
{"Rapper":"Fat Joe","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"fat","Intelligence":"Dumb","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Pull up your pants, you're Fat Joe!"},
{"Rapper":"MF Doom","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Food_Fitness_BodyType":"fat","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"The mystery is finally solved! You, of all people, are MF DOOM."},
{"Rapper":"Afrika Bambaataa","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Food_Fitness_BodyType":"fat","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"Welcome to Planet Rock, you are Afrika Bambaataa."},
{"Rapper":"Big Pun","Decade":"1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"fat","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You're not a player, you just fuck a lot. You're Big Pun!"},
{"Rapper":"Action Bronson","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"fat","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed, Cocaine","ResultText":"You're posted up in the Galapagos, higher than an opera note; you're Action Bronson!"},
{"Rapper":"Chuck  D","Decade":"1980's, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"Fat","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You are Public Enemy number one."},
{"Rapper":"Schoolboy Q","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"many","Food_Fitness_BodyType":"Fat","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Drug dealer","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Pills, Weed","ResultText":"Look up in the sky, it's a bird, it's a plane... no, it's just you, Schoolboy Q."},
{"Rapper":"J. Cole","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"t shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Pussy Whipped","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"You let Nas down; you're J. Cole."},
{"Rapper":"Joey Bada$$","Decade":"2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"a few","Food_Fitness_BodyType":"skinny","Intelligence":"Smart","PimpHand":"wouldn't you like to know","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor, Beer","DrugOfChoice":"Weed","ResultText":"You're the 19-year-old OG Swanklord. You're Joey Bada$$"},
{"Rapper":"Ja Rule","Decade":"2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Your pimp game is very religious. You're Ja Rule."},
{"Rapper":"Redman","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Your crew does drugs Duane Reade couldn't breed. You're Redman."},
{"Rapper":"Busta Rhymes","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Woo hah!! You've got us all in check. You're Busta Rhymes."},
{"Rapper":"Lauryn Hill","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You've got "},
{"Rapper":"Method Man","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"Athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You don't eat green eggs and ham, because you're Method Man!"},
{"Rapper":"Ghostface Killah","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"Fat","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You're Tony Starks AKA Ghostdeini AKA Pretty Toney AKA Ghostface Killah."},
{"Rapper":"A$AP Rocky","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"a few","Food_Fitness_BodyType":"skinny","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Molly","ResultText":"You're A$AP Rocky, you pretty motherfucker, you."},
{"Rapper":"French Montana","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"average","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Cocaine","ResultText":"You, my friend, are a cocaine connoisseur. You're French Montana."},
{"Rapper":"Lil Wayne","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"facial","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Legit pimp","CriminalHistory":"Minor","Sound":"Dirty South","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Lean, Weed","ResultText":"You've been handling the game so long, your thumb's bruised. You're Lil Wayne."},
{"Rapper":"Gucci Mane","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"facial","Food_Fitness_BodyType":"average","Intelligence":"Mentally incompetent","PimpHand":"Legit pimp","CriminalHistory":"Might have killed someone","Sound":"Dirty South, Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Lean, Pills","ResultText":"Better wear a coat, beacuse... Burr! You're Gucci Mane!"},
{"Rapper":"T- Pain","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Food_Fitness_BodyType":"average","Intelligence":"Dumb","PimpHand":"no standards","CriminalHistory":"None","Sound":"Dirty South, Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You fucked a mermaid! You are T-Pain. "},
{"Rapper":"Future","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"Minor","Sound":"Pop, Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Molly","ResultText":"I'm just being honest, you are Future!"},
{"Rapper":"Andre 3000","Decade":"1990s, 2000s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"Stank you smelly much for playing, you are André 3000!"},
{"Rapper":"Childish Gambino","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Hipster","Tattoos":"none","Food_Fitness_BodyType":"average","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed, Acid","ResultText":"You're Childish Gambino because, well, the internet."},
{"Rapper":"Ludacris","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","ResultText":"Welcome to Atlanta, Ludacris."},
{"Rapper":"Big Krit","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South, Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","ResultText":"You must be on some country shit, because you're Big K.R.I.T."},
{"Rapper":"Rick Ross","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"fat","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"Welcome to the boss life, you are Rick Ross!"},
{"Rapper":"Missy Elliot","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Food_Fitness_BodyType":"fat","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Supa dupa fly, you're Missy Elliot!"},
{"Rapper":"2 Pac","Decade":"1990s","Region":"West Coast","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Thug life."},
{"Rapper":"Paul Wall","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"many","Food_Fitness_BodyType":"fat","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Lean","ResultText":"You open up your mouth and see more carats than a salad. You are Paul Wall!"},
{"Rapper":"Vanilla Ice","Decade":"1990s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Classic, Pop","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"None","ResultText":"Word to your mother.  You're Vanilla Ice!"},
{"Rapper":"Riff Raff","Decade":"2000s, 2010s","Region":"East Coast, Dirty South, West Coast","Fashion":"Avant-garde","Tattoos":"many","Food_Fitness_BodyType":"skinny","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Minor, Drug possession","Sound":"Trap, Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed, Molly, Cocaine","ResultText":"You are the Neon Icon! The rap game Farrah Fawcett!"},
{"Rapper":"Kanye West","Decade":"2000s, 2010s","Region":"East Coast, Mid West, Dirty South","Fashion":"Avant-garde","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Pussy whipped","CriminalHistory":"Assault","Sound":"Always changing","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You'd rather be a dick than a swallower. You're Kanye West!"},
{"Rapper":"Mac Miller","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"many","Food_Fitness_BodyType":"skinny","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Drug possession","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Acid","ResultText":"You're not Donald Trump, you're Mac Miller!"},
{"Rapper":"Nas","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Minor","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Break out the Hennessy, you're Nas!"},
{"Rapper":"Dr. Dre","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"Athletic","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You still take time to perfect the Beats™. You're Dr. Dre."},
{"Rapper":"50 Cent","Decade":"2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Pop, Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"You got rich, and didn't die trying. You're 50 Cent."},
{"Rapper":"MC Hammer","Decade":"1980s, 1990s","Region":"West Coast","Fashion":"Avant-garde","Tattoos":"none","Food_Fitness_BodyType":"athletic","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"None","ResultText":"Stop. Hammer time!"},
{"Rapper":"Jay-Z","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"Drug dealer","Sound":"Always changing, Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","ResultText":"Jigga what?  Jigga who?  You're Jay Z!"},
{"Rapper":"Slick Rick","Decade":"1980s, 1990s, 2000s","Region":"East Coast","Fashion":"Upscale","Tattoos":"none","Food_Fitness_BodyType":"Skinny","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Pills, Weed","ResultText":"La di da di, it's time to party!  You're Slick Rick!"},
{"Rapper":"LL Cool J","Decade":"1980s, 1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Food_Fitness_BodyType":"athletic","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","ResultText":"Ladies must love you, you're LL Cool J!"},
{"Rapper":"Snoop Dogg","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Food_Fitness_BodyType":"athletic","Intelligence":"Smart","PimpHand":"Legit pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"You're laid back, with your mind on your money on your mind. You're Snoop Dogg!"},
{"Rapper":"The Notorious B.I.G.","Decade":"1990s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Food_Fitness_BodyType":"fat","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","ResultText":"Throw your hands in the air if you're a true player, you are Big Poppa!"}];


	var data_index = 0;
	for (rapper in data) {
		rapper["Index"] = data_index;
		data_index++;
	}
	
	$("#submitButton").click(function() {
		var r = getSubmit(data);
			$("#content").html(r);
			$("html, body").animate({scrollTop: 0}, "slow");
		});

		//getSubmit(data);
		
		test_parse(data);

} //end main_wp

$(window).load(function() {
	main_wp();
	console.log("ready");
});
