/*
 * MAINDO
 */

//For local / usdivad.com
function main_local() {
	//var rappers;

	//JSON req
	$.getJSON("./src/rapper_stats.json", function(data) {
		//rappers = data;
		//$("#inputForm").append(createForm(data, allParams));
		$("#submitButton").click(function() {
			var r = getSubmit(data);
			$("#results").html(r);
		});
		//getSubmit(data);
		test_parse(data);

	}); //end JSON req
}

//For Wordpress integration
function main_wp() {

	var data = [{"Rapper":"Snoop Dogg","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You're laid back, with your mind on your money on your mind. Your rap personality is Snoop Dogg!"},
{"Rapper":"The Notorious B.I.G.","Decade":"1990s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Eating","ResultText":"Throw your hands in the air if you're a true player, your rap personality is Big Poppa!"},
{"Rapper":"Kendrick Lamar","Decade":"2010s","Region":"West Coast","Fashion":"Hipster","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Always changing","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"Macklemore thinks you're awesome. Your rap personality is Kendrick Lamar."},
{"Rapper":"MC Hammer","Decade":"1980s, 1990s","Region":"West Coast","Fashion":"Avant-garde","Tattoos":"none","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"Stop. Hammer time! Your rap personality is MC Hammer!"},
{"Rapper":"Andre 3000","Decade":"1990s, 2000s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Playing video games","ResultText":"Stank you smelly much for playing, your rap personality is André 3000!"},
{"Rapper":"Danny Brown","Decade":"2010s","Region":"Mid West","Fashion":"Hipster","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Drug dealer, Drug possession","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Molly, Weed","Zone":"Getting your freak on","ResultText":"Like Lieutenant Dan, you're rolling. Your rap personality is Danny Brown."},
{"Rapper":"Insane Clown Posse","Decade":"1990s, 2000s, 2010s","Region":"Mid West","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Underground/alternative","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Crack, Pills","Zone":"Eating","ResultText":"Fuckin' quizzes, how do they work? Your rap personality is ICP!"},
{"Rapper":"Drake","Decade":"2000s, 2010s","Region":"East Coast, Dirty South, Mid West","Fashion":"Avant-garde","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop, Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"Better be on your worst behavior, because your rap personality is Drake."},
{"Rapper":"Jay-Z","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"Drug dealer","Sound":"Always changing, Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Making money","ResultText":"Jigga what?  Jigga who?  Your rap personality is Jay Z!"},
{"Rapper":"Kanye West","Decade":"2000s, 2010s","Region":"East Coast, Mid West, Dirty South","Fashion":"Avant-garde","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Pussy whipped","CriminalHistory":"Assault","Sound":"Always changing","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"You'd rather be a dick than a swallower. Your rap personality is Kanye West!"},
{"Rapper":"Eminem","Decade":"1990s, 2000s, 2010s","Region":"East Coast, Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Assault","Sound":"Pop, Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"none","Zone":"Fighting","ResultText":"Your rap personality is the real Slim Shady. Please stand up."},
{"Rapper":"Beastie Boys","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","Zone":"Building a stronger community","ResultText":"Your rap personality is the Beastie Boys, and you're now officially liscensed to ill."},
{"Rapper":"2 Pac","Decade":"1990s","Region":"West Coast","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"Thug life.  Your rap personality is 2Pac."},
{"Rapper":"Lil Wayne","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"facial","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Minor","Sound":"Dirty South","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Lean, Weed","Zone":"Getting your freak on","ResultText":"You've been handling the game so long, your thumb's bruised. Your rap personality is Lil Wayne."},
{"Rapper":"Afrika Bambaataa","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"Welcome to Planet Rock, your rap personality is Afrika Bambaataa."},
{"Rapper":"Action Bronson","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed, Cocaine","Zone":"Eating","ResultText":"You're posted up in the Galapagos, higher than an opera note. Your rap personality is Action Bronson!"},
{"Rapper":"Vanilla Ice","Decade":"1990s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Classic, Pop","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"None","Zone":"Making money","ResultText":"Word to your mother.  Your rap personality is Vanilla Ice!"},
{"Rapper":"Riff Raff","Decade":"2000s, 2010s","Region":"East Coast, Dirty South, West Coast","Fashion":"Avant-garde","Tattoos":"many","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Minor, Drug possession","Sound":"Trap, Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed, Molly, Cocaine","Zone":"Chilling","ResultText":"Your rap personality is RiFF RaFF! The rap game Farrah Fawcett!"},
{"Rapper":"Mac Miller","Decade":"2000s, 2010s","Region":"East Coast, Mid West","Fashion":"Hipster","Tattoos":"many","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Drug possession","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Acid","Zone":"Chilling","ResultText":"You're not Donald Trump, your rap personality is Mac Miller!"},
{"Rapper":"J. Cole","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"t shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"Pussy Whipped","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You let Nas down, then made him proud. Your rap personality is J. Cole."},
{"Rapper":"Chance The Rapper","Decade":"2010s","Region":"Mid West","Fashion":"Hipster","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Acid","Zone":"Playing video games","ResultText":"You like LSD so much, you named a mixtape after it. Your rap personality is Chance the Rapper."},
{"Rapper":"Macklemore","Decade":"2000s, 2010s","Region":"West Coast","Fashion":"Avant-garde","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"You're the guy in the fur coat with all the Grammys. Your rap personality is Macklemore."},
{"Rapper":"Nas","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"many","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Minor","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"Break out the Hennessy, your rap personality is Nas!"},
{"Rapper":"Dr. Dre","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Making money","ResultText":"You still take time to perfect the Beats™. Your rap personality is Dr. Dre."},
{"Rapper":"Rick Ross","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Eating","ResultText":"Welcome to the boss life, your rap personality is Rick Ross!"},
{"Rapper":"50 Cent","Decade":"2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Pop, Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Making money","ResultText":"You got rich, and didn't die trying. Your rap personality is 50 Cent."},
{"Rapper":"Redman","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"Your crew does drugs Duane Reade couldn't breed. Your rap personality is Redman."},
{"Rapper":"Tyler, The Creator","Decade":"2000s, 2010s","Region":"West Coast","Fashion":"Hipster","Tattoos":"a few","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Playing video games","ResultText":"You'd like to stab Bruno Mars in his esophagus. Your rap personality is Tyler, the Creator!"},
{"Rapper":"Schoolboy Q","Decade":"2000s, 2010s","Region":"West Coast","Fashion":"Hipster","Tattoos":"many","Intelligence":"Street smart","PimpHand":"no standards","CriminalHistory":"Drug dealer","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Pills, Weed","Zone":"Making money","ResultText":"Look up in the sky, it's a bird, it's a plane... no, it's just you, Schoolboy Q."},
{"Rapper":"Wale","Decade":"2000s, 2010s","Region":"East Coast, Dirty South","Fashion":"Upscale","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Pussy Whipped","CriminalHistory":"None","Sound":"Pop, Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You went from hipster to gangster in less than sixty secords.  Your rap personality is Wale!"},
{"Rapper":"Pusha T","Decade":"1990s, 2000s, 2010s","Region":"East Coast, Dirty South","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Cocaine","Zone":"Making money","ResultText":"You might sell a brick on your birthday. Your rap personality is Pusha T."},
{"Rapper":"2 Chainz","Decade":"2000s, 2010s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Legit Pimp","CriminalHistory":"Drug dealer, Drug possession","Sound":"Trap, Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Cocaine","Zone":"Making money","ResultText":"Better step up your neck jewelery game, because your rap personality is 2 Chainz!"},
{"Rapper":"Q-Tip","Decade":"1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"You're abstract, and we're not talking about Picasso. Your rap personality is Q-Tip."},
{"Rapper":"Busta Rhymes","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Working out","ResultText":"Woo hah!! You've got us all in check. Your rap personality is Busta Rhymes."},
{"Rapper":"Dmx","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed, Cocaine, Crack","Zone":"Working out","ResultText":"Your Wikipedia "},
{"Rapper":"Ol' Dirty Bastard","Decade":"1990s","Region":"East Coast","Fashion":"t shirt & Jeans","Tattoos":"a few","Intelligence":"Mentally incompetent","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Crack, Cocaine","Zone":"Fighting","ResultText":"Your rap personality is the Osiris of this shit, AKA Ol' Dirty Bastard."},
{"Rapper":"Black Thought","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","Zone":"Building a stronger community","ResultText":"On your first day of high school, you had sex with a senior in the bathroom. Your rap personality is Black Thought."},
{"Rapper":"Mos Def","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"Your rap personality is most definitely Mos Def."},
{"Rapper":"Talib Kweli","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Building a stronger community","ResultText":"Kanye used to name-drop you to pick up girls. Your rap personality is Talib Kweli."},
{"Rapper":"Madlib","Decade":"1990s, 2000s, 2010s","Region":"West Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Playing video games","ResultText":"You must be one of America's Most Blunted, because your rap personality is Madlib!"},
{"Rapper":"Wiz Khalifa","Decade":"2000s, 2010s","Region":"East Coast, Mid West","Fashion":"Hipster","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You are Kanye's eskimo bro, Wiz Khalifa."},
{"Rapper":"A$AP Rocky","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Underground/alternative","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Molly","Zone":"Fighting","ResultText":"Your rap personality is A$AP Rocky, you pretty motherfucker, you."},
{"Rapper":"A$AP Ferg","Decade":"2000s, 2010s","Region":"Mid West, East Coast","Fashion":"Hipster","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Trap","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You must be a Trap Lord and/or Hood Pope, because your rap personality is A$AP Ferg!"},
{"Rapper":"Childish Gambino","Decade":"2000s, 2010s","Region":"West Coast, Dirty South","Fashion":"Hipster","Tattoos":"none","Intelligence":"Smart","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Beer","DrugOfChoice":"Weed, Acid","Zone":"Playing video games","ResultText":"Your rap personality is Childish Gambino because, well, the internet."},
{"Rapper":"Bone Thugs N Harmony","Decade":"1990s, 2000s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Assault","Sound":"Dirty South, Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You are Krayzie, Layzie, Bizzy, Wish and Flesh-n all rolled into one. Your rap personality is Bone Thugs N Harmony!"},
{"Rapper":"Nicki Minaj","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"None","Zone":"Making money","ResultText":"You've got the largest barbie collection in the world. Your rap personality is Nicki Minaj."},
{"Rapper":"Deltron 3030","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"None","Zone":"Playing video games","ResultText":"In the year 3030, everybody wants to be you. Your rap personality is Deltron 3030!"},
{"Rapper":"Run-D.M.C.","Decade":"1980s, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Making money","ResultText":"Peter Piper picked peppers, Run rocked rhymes, and you just took a quiz. Your rap personality is Run-DMC!"},
{"Rapper":"MF Doom","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Playing video games","ResultText":"The mystery is finally solved! You, of all people, are MF DOOM."},
{"Rapper":"Chuck  D","Decade":"1980's, 1990s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"Minor","Sound":"Classic, Underground/alternative","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Building a stronger community","ResultText":"You are Public Enemy number one.  Your rap personality is Chuck D."},
{"Rapper":"Joey Bada$$","Decade":"2010s","Region":"East Coast","Fashion":"Hipster","Tattoos":"a few","Intelligence":"Smart","PimpHand":"no standards","CriminalHistory":"None","Sound":"Underground/alternative","DrinkOfChoice":"Bottom shelf liquor, Beer","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"You're the 19-year-old OG Swanklord. Your rap personality is Joey Bada$$"},
{"Rapper":"Lauryn Hill","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"none","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Building a stronger community","ResultText":"You've got "},
{"Rapper":"Future","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"Minor","Sound":"Pop, Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Molly","Zone":"Making money","ResultText":"I'm just being honest, your rap personality is Future!"},
{"Rapper":"Method Man","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Beer, Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"You don't eat green eggs and ham, because your rap personality is Method Man!"},
{"Rapper":"Ghostface Killah","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Chilling","ResultText":"Your rap personality is Tony Starks AKA Ghostdeini AKA Pretty Toney AKA Ghostface Killah."},
{"Rapper":"French Montana","Decade":"2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Cocaine","Zone":"Getting your freak on","ResultText":"You, my friend, are a cocaine connoisseur. Your rap personality is French Montana."},
{"Rapper":"Gucci Mane","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"facial","Intelligence":"Mentally incompetent","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Dirty South, Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Lean, Pills","Zone":"Fighting","ResultText":"Better wear a coat, beacuse... Burr! Your rap personality is Gucci Mane!"},
{"Rapper":"Nelly","Decade":"1990s, 2000s, 2010s","Region":"Mid West","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Dumb","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Working out","ResultText":"Is it hot in herre, or is it just you? Your rap personality is Nelly!"},
{"Rapper":"T- Pain","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Avant-garde","Tattoos":"many","Intelligence":"Dumb","PimpHand":"no standards","CriminalHistory":"None","Sound":"Dirty South, Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Getting your freak on","ResultText":"You fucked a mermaid! Your rap personality is T-Pain. "},
{"Rapper":"Ludacris","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South","DrinkOfChoice":"Beer","DrugOfChoice":"Weed","Zone":"Getting your freak on","ResultText":"What's your fantasy?  Your rap personality is Ludacris."},
{"Rapper":"Big K.R.I.T.","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South, Underground/alternative","DrinkOfChoice":"Bottom shelf liquor","DrugOfChoice":"Weed","Zone":"Building a stronger community","ResultText":"You must be on some country shit, because your rap personality is Big K.R.I.T."},
{"Rapper":"Missy Elliot","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Avant-garde","Tattoos":"none","Intelligence":"Smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Getting your freak on","ResultText":"Supa dupa fly, your rap personality is Missy Elliot!"},
{"Rapper":"Paul Wall","Decade":"2000s, 2010s","Region":"Dirty South","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Street smart","PimpHand":"Semi-Pimp","CriminalHistory":"None","Sound":"Dirty South","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed, Lean","Zone":"Chilling","ResultText":"You open up your mouth and see more carats than a salad. Your rap personality is Paul Wall!"},
{"Rapper":"Slick Rick","Decade":"1980s, 1990s, 2000s","Region":"East Coast","Fashion":"Upscale","Tattoos":"none","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Pills, Weed","Zone":"Fighting","ResultText":"La di da di, it's time to party!  Your rap personality is Slick Rick!"},
{"Rapper":"Chief Keef","Decade":"2010s","Region":"Mid West","Fashion":"Thuggin'","Tattoos":"many","Intelligence":"Mentally incompetent","PimpHand":"Legit Pimp","CriminalHistory":"Might have killed someone, Drug dealer","Sound":"Trap","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"Bang bang! Stay out of trouble, Chief Keef."},
{"Rapper":"Fat Joe","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Dumb","PimpHand":"no standards","CriminalHistory":"Might have killed someone","Sound":"Classic","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Eating","ResultText":"Pull up your pants, your rap personality is Fat Joe!"},
{"Rapper":"P Diddy","Decade":"1990s, 2000s, 2010s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Smart","PimpHand":"Legit Pimp","CriminalHistory":"Minor","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Making money","ResultText":"You're a Bad Boy for life, no matter how many times you change your name.  Your rap personality is P. Diddy."},
{"Rapper":"Ja Rule","Decade":"2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"many","Intelligence":"Dumb","PimpHand":"Pussy whipped","CriminalHistory":"None","Sound":"Pop","DrinkOfChoice":"Top shelf liquor","DrugOfChoice":"Weed","Zone":"Working out","ResultText":"Your pimp game is very religious. Your rap personality is Ja Rule."},
{"Rapper":"LL Cool J","Decade":"1980s, 1990s, 2000s","Region":"East Coast","Fashion":"T shirt & Jeans","Tattoos":"a few","Intelligence":"Street smart","PimpHand":"Legit Pimp","CriminalHistory":"Assault","Sound":"Classic","DrinkOfChoice":"Mountain Dew","DrugOfChoice":"None","Zone":"Working out","ResultText":"Ladies must love you, your rap personality is LL Cool J!"},
{"Rapper":"Lil' Kim","Decade":"1990s, 2000s","Region":"East Coast","Fashion":"Upscale","Tattoos":"a few","Intelligence":"Dumb","PimpHand":"Legit Pimp","CriminalHistory":"Minor","Sound":"Pop","DrinkOfChoice":"Champagne/Wine","DrugOfChoice":"Weed","Zone":"Fighting","ResultText":"According to Ben Stiller, you're phat. Your rap personality is Lil' Kim."}];


	var data_index = 0;
	for (rapper in data) {
		rapper["Index"] = data_index;
		data_index++;
	}
	
	$("#submitButton").click(function() {
		var r = getSubmit(data);
			$("#content").html(r);
			$("html, body").animate({scrollTop: 0}, "slow");
		});

		//getSubmit(data);
		
		test_parse(data);

} //end main_wp

$(window).load(function() {
	main_wp();
	console.log("ready");
});
